@extends('layouts.header_and_footer')
@section('body')
    <title> {{$name}}  </title>
    <div class="privacy-policy">
        <div class="privacy-policy-head">
            <div class="privacy-policy-title">
                PRIVACY POLICY
            </div>
        </div>
        <div class="privacy-policy-body">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est explicabo perferendis eos amet ducimus, expedita praesentium nesciunt aut, voluptas enim commodi. Iure ipsa suscipit odit nesciunt ducimus eligendi quo tempore! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Unde maxime reprehenderit ad, vitae error accusantium facere sit, veritatis soluta a possimus eaque delectus tenetur cum temporibus aut ducimus eveniet laboriosam iste, alias praesentium! Eum obcaecati maiores deserunt eos laudantium soluta reprehenderit, quam dignissimos. Vitae laboriosam natus nemo laborum id iste temporibus illo odio quisquam error tenetur unde aliquam, quaerat magni voluptatem accusamus ipsam pariatur animi maiores mollitia. Alias aliquid illum sit! Aliquam inventore sapiente quisquam provident, omnis nostrum labore vel eum at quidem possimus, ratione accusantium. Corporis animi natus deserunt impedit non consectetur neque tempora amet ut nulla rem maxime, perspiciatis fugit quia quae esse maiores odio dolores. Repellat quo est nobis cupiditate facere debitis accusamus iste adipisci tempora! Possimus iusto corrupti aperiam natus autem quae vitae, minima nam porro ipsam quis eveniet illo corporis? Commodi eum et fugiat eius doloribus! Perferendis quisquam obcaecati facilis aliquam, nesciunt culpa sed placeat alias laudantium deserunt quam mollitia error eum commodi. Architecto quam cupiditate maiores, corporis animi tenetur veniam et numquam tempora, sit perspiciatis officiis laudantium officia blanditiis eveniet quisquam dolores dolorum nostrum magni ab? Quidem voluptatibus recusandae molestias neque nobis voluptate earum accusantium dolorum eaque praesentium corporis vero, qui, quos illo ea.

            <br> <br> <br>

            Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo ea saepe facilis quod nihil nostrum a consequatur veniam laborum, maiores mollitia error sequi dolores vel eligendi, molestias voluptates! Repellat ab natus totam sapiente in, nisi maxime laborum voluptatum! Consectetur distinctio aspernatur eveniet dolores quae, error numquam quis dolorum vero explicabo nisi voluptate officia odit ullam quisquam iste animi placeat, exercitationem est. Sint inventore reiciendis aspernatur! Ullam illo voluptatibus eveniet nihil facilis temporibus est iste quam expedita aut mollitia beatae rem minus cum velit, rerum cumque molestiae, quos ab nulla, possimus repellat. Voluptatum facere impedit, unde repellat recusandae sequi, consequuntur quod autem, adipisci sint deserunt quo architecto aperiam nam sit id quia. Fugiat nam ea neque corporis rem. Fuga, sit aliquam ipsa delectus voluptates omnis? Quae nesciunt aspernatur voluptatum hic in numquam dolorem molestias tempora et, perspiciatis cumque iure veritatis amet, id dolores adipisci natus corrupti ut, labore quibusdam quam? Quam maiores numquam labore molestias possimus dolorum doloremque inventore omnis debitis eum quidem, voluptatem eaque, corrupti tempora rerum sapiente excepturi quod assumenda. Itaque autem sapiente esse nesciunt distinctio fuga assumenda quidem odit illum culpa, eius iure error voluptatum necessitatibus illo rem dolor? Aut rerum placeat, sit minus excepturi vero deleniti suscipit.

            <br> <br> <br>

            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora at, repudiandae maiores excepturi facere qui aperiam dignissimos quia dolores iure voluptatibus et dolorem atque, quas minima est, ducimus veritatis cum voluptates? Consequuntur quo aliquid quos blanditiis, deserunt neque nesciunt laborum cumque minima. Impedit accusantium quibusdam quas nihil tempora. Dicta molestias illo ducimus temporibus porro sapiente, vel exercitationem, quis ab voluptate impedit quisquam. Sequi minus perferendis repellat ab amet! Quod adipisci vel incidunt delectus, quam, consectetur iure esse fuga qui voluptates tenetur quas asperiores inventore id sed similique eos in. Dolores ducimus dolorum quasi quo quibusdam! Excepturi dolorem deserunt reiciendis ut praesentium non facere est voluptate quis consectetur soluta nam in ex saepe earum quas incidunt voluptas, at tempore sed dolore doloremque, sequi velit. Quas enim totam eum consectetur nesciunt explicabo harum ipsa reprehenderit. Recusandae beatae qui provident alias veniam, ullam labore. Possimus impedit ipsa nam eaque quia odit eum obcaecati commodi aliquid pariatur iusto eius distinctio, deserunt reprehenderit aut, fugiat aspernatur nisi magnam maxime ratione architecto ab dolore consequuntur. Veritatis itaque molestiae, nihil sit error inventore, vero saepe nostrum rerum illum mollitia quaerat doloremque ipsam illo porro accusamus vel libero, dolorem consequatur. Quae molestiae pariatur ipsam architecto perferendis minima officia?
        </div>
    </div>
@endsection